
def show_login(window, canvas, bot, start_btn, back, username_entry, password_entry, login, signup_link, signup, login_link, reg_username_entry, reg_email_entry, reg_password_entry, background_img, login_heading, username, password):

    window.title("Desktop Assistant | Login")
    canvas.delete('heroTitle')
    bot.place_forget()
    canvas.delete('create')
    canvas.delete('update')
    canvas.delete('read')
    canvas.delete('delete')
    canvas.delete('email')
    start_btn.place_forget()
    canvas.create_image(232, 315, image=background_img, tag='background')
    canvas.create_image(730, 180, image=login_heading, tag='login_title')
    back.place(x=485, y=30)
    canvas.delete('username')
    canvas.delete('password')
    canvas.create_image(730, 300, image=username, tag='username')
    canvas.create_image(730, 400, image=password, tag='password')
    username_entry.place(x=572.0, y=290, width=321.0, height=50)
    password_entry.place(x=572.0, y=370+20, width=321.0, height=50)
    login.place(x=670, y=460)
    signup_link.place(x=622, y=515)
    canvas.delete('signup_title')
    signup.place_forget()
    login_link.place_forget()
    reg_username_entry.place_forget()
    reg_email_entry.place_forget()
    reg_password_entry.place_forget()


def show_cover(window, canvas, bot, start_btn, back, username_entry, password_entry, login, signup_link, signup, login_link, reg_username_entry, reg_email_entry, reg_password_entry, hero_title, update_img, delete_img, read_img, create_img):

    window.title("Desktop Assistant")
    bot.place(x=335, y=355)
    canvas.delete('background')
    canvas.delete('login_title')
    back.place_forget()
    login.place_forget()
    signup_link.place_forget()
    username_entry.place_forget()
    password_entry.place_forget()
    reg_username_entry.place_forget()
    reg_email_entry.place_forget()
    reg_password_entry.place_forget()
    canvas.delete('username')
    canvas.delete('password')
    canvas.create_image(500, 180, image=hero_title, tag='heroTitle')
    canvas.create_image(790, 520, image=update_img, tag='update')
    canvas.create_image(165, 520, image=delete_img, tag='delete')
    canvas.create_image(750, 410, image=read_img, tag='read')
    canvas.create_image(235, 380, image=create_img, tag='create')
    start_btn.place(x=435, y=290)
    canvas.delete('signup_title')
    canvas.delete('email')
    login_link.place_forget()
    signup.place_forget()


def show_signup(window, canvas, username_entry, password_entry, login, signup_link, signup, login_link, reg_username_entry, reg_email_entry, reg_password_entry, username, email, password, signup_heading):

    window.title("Desktop Assistant | Signup")
    canvas.delete('login_title')
    login.place_forget()
    signup_link.place_forget()
    username_entry.place_forget()
    password_entry.place_forget()
    canvas.delete('username')
    canvas.delete('password')
    canvas.create_image(730, 250, image=username, tag='username')
    canvas.create_image(730, 350, image=email, tag='email')
    canvas.create_image(730, 450, image=password, tag='password')
    canvas.create_image(700, 145, image=signup_heading, tag='signup_title')
    signup.place(x=665, y=510)
    login_link.place(x=622, y=562)
    reg_username_entry.place(x=572.0, y=240, width=321.0, height=50)
    reg_email_entry.place(x=572.0, y=340, width=321.0, height=50)
    reg_password_entry.place(x=572.0, y=440, width=321.0, height=50)
